INSERT INTO `game` (`id`, `name`, `description`) VALUES
(1, 'penguin', 'The penguin game is a simple infinite runner, which sees you jump over different obstacles.'),
(2, 'arkanoid', 'An aweasome description of some game.'),
(3, 'arkanoid_old', 'An aweasome description of some game.'),
(4, 'chicken', 'An aweasome description of some game.'),
(5, 'head_game', 'An aweasome description of some game.'),
(6, 'ship_game', 'An aweasome description of some game.'),
(7, 'snake', 'An aweasome description of some game.'),
(8, 'buscaminas', 'An aweasome description of some game.'),
(9, 'calavera', 'An aweasome description of some game.'),
(10, 'gallinita', 'An aweasome description of some game.'),
(11, 'chicken_road', 'An aweasome description of some game.'),
(12, 'pollhor', 'An aweasome description of some game.'),
(13, 'pinball', 'An aweasome description of some game.'),
(14, 'twicecard', 'An aweasome description of some game.');